# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'MinhMonHello', :git => 'https://github.com/minmon98/MinhMonHello.git', :tag => '1.0.0'
end
